          version: 0.2
          phases:
            install:
              runtime-versions:
                docker: 18
            pre_build:
              commands:
                - echo Retrieving information from artifacts...
            build:
              commands:
                - echo Building the parameters file.......
            post_build:
              commands:
                - echo source code to s3
                - zip -r lambda.zip lambda
                - aws s3 cp --recursive lambda s3://lambda-layer-tst/

   
