          version: 0.2
          phases:
            install:
              runtime-versions:
                docker: 18
            pre_build:
              commands:
                - echo Retrieving information from artifacts...
            build:
              commands:
                - echo Building the parameters file.....
            post_build:
              commands:
                - echo source code to s3
                - zip  lambda.zip lambda/lambda-sub
                - aws s3 cp --recursive lambda.zip s3://lambda-layer-tst/

   
