version: 0.2
phases:
    install:
      runtime-versions:
        python: 3.8
    #pre_build:
      #  commands:
       #  - pip install --upgrade awscli
    build:
        commands:
        - echo "Installing dependencies..."
         #- chmod 777 requirements.sh
         #- bash requirements.sh
         - ls -ltr
         - zip  lambda/lambda_function.zip lambda/lambda_function.py
         - echo "copy lambda Function..."
       #  - aws lambda update-function-code  --function-name  lambda_function --zip-file fileb://lambda.zip --region us-east-1
         - aws s3 cp  --recursive lambda s3://lambda-layer-tst/
         - echo "DONE!!"
   
