version: 0.2
phases:
    install:
      runtime-versions:
        python: 3.8
    pre_build:
        commands:
         - pip install --upgrade awscli
    build:
        commands:
         - echo "Installing dependencies..."
         #- chmod 777 requirements.sh
         #- ./requirements.sh
         - ls -ltr
         - zip -r9 lambda.zip lambda_function.py
         - echo "Updating lambda Function..."
         - aws lambda update-function-code  --function-name  test22 --zip-file fileb://lambda.zip --region us-east-1
         - echo "DONE!!"
