Parameters:
  VPCId:
    Description: VPC to create the security group and EC2 instance 
    Type: AWS::EC2::VPC::Id
    Default: vpc-8b3fe0f6

Mappings:
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0dc2d3e4c0f9ebd18

Resources:

  SSHSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/vasantha01/lambda-repo/blob/cp/ssh-security-group.yaml
      Parameters:
        ApplicationName: !Ref AWS::StackName
        VPCId: !Ref VPCId
      TimeoutInMinutes: 5


  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      # Note we use the pseudo parameter AWS::Region
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', HVM64]
      AvailabilityZone: !Sub ${AWS::Region}a
      SecurityGroupIds:
        - !GetAtt SSHSecurityGroupStack.Outputs.SSHGroupId

