AWSTemplateFormatVersion: 2010-09-09
   Description: S3-BucketCreation
   Resources: 
     S3Bucket: 
            Type: AWS::S3::Bucket
	    Properties:
     Outputs:
	    BucketName:
	    Value: !Ref S3Bucket
   
            
        
